### ISSUE TITLE
Mashlib Recipe: How to make the "sign up" button work "properly"?

### ISSUE THREAD

**Issue by renyuneyun** [CommunitySolidServer/Recipes#28]
When using the Mashlib recipe, the big "Sign up for Solid" button in the top right corner leads to https://solidproject.org//users/get-a-pod. However, intuitively, it should go to the sign-up page of the current CSS instance.

Can this behaviour be customized? Is this more a recipe issue or mashlib issue?
I can supply the URL of the sign-up page, if it cannot be figured out automatically.

**Comment by bourgeoa** [comment]
Thanks for reporting. It is a mashlib issue. There are no optional parameters on mashlib.

**Comment by joachimvh** [comment]
Closing this as it's a Mashlib issue.
