### ISSUE TITLE
is 7.0.4 a breaking change ?

### ISSUE THREAD

**Issue by bourgeoa** [CommunitySolidServer/Recipes#35]
`start script` : npx community-solid-server moved to npx @solid/community-server

**Comment by joachimvh** [comment]
Upgrading to v7.0.4 should have no impact at all. It only changes some typing dependencies which have an impact for people who interact with the package directly thorugh code.

**Comment by bourgeoa** [comment]
shall be closed by https://github.com/CommunitySolidServer/Recipes/pull/36
